[general]
  selection = ["cy49t2_alaro", "cy49t2_alaro_target"]
  tag = "33d75b0_"

  # Uncomment this for intel and gnu runs
  #subtags = [
    #{intel_ = []},
    #{gnu_ = ["deode/data/config_files/modifications/submission/atos_bologna_gnu.toml"]},
  #]

[ial]
  bindir = "/scratch/@USER@/ial_binaries/@IAL_HASH@/@COMPILER@/@PRECISION@/bin"
  build_tar_path = "/scratch/deployde330"
  ial_hash = "33d75b06b0bf09a01246d1e14ffae42334399af6"

[include]
  cases = "case_definitions.toml"

[macros.case]
  gen_macros = [{ial_hash = "ial.ial_hash"}]
  group_macros = []
  os_macros = ["USER"]

[macros.select.default]
  gen_macros = []
  group_macros = ["modif_macros"]
  os_macros = ["USER"]

[modifs.cleaning.PostMortem.ecf_files]
  active = false

[modifs.general.times]
  # counter for starting days, this is to test different days
  end = "-P@COUNTER@D"
  start = "-P@COUNTER@D"

[modifs.submission]
  bindir = "/scratch/@USER@/ial_binaries/@IAL_HASH@/@COMPILER@/R64/bin"
  max_ecf_tasks = 25

[modifs.submission.task_exceptions.Forecast]
  bindir = "/scratch/@USER@/ial_binaries/@IAL_HASH@/@COMPILER@/@PRECISION@/bin"

[modifs.system]
  # Picks up the case name and domain from the host run
  host_case = "@HOST_CASE@"
  host_domain = "@HOST_DOMAIN@"
