[general]
  selection = [
    "cy49t2_alaro",
    "cy49t2_alaro_target",
    "cy49t2_alaro_eps",
    "cy49t2_arome",
    "cy49t2_arome_dp",
    "cy49t2_arome_eps",
    "cy49t2_arome_flooding",
    "cy49t2_arome_target",
    "cy49t2_arome_use_offline",
    "cy49t2_harmonie_arome",
    "cy49t2_harmonie_arome_airquality",
    "cy49t2_harmonie_arome_dp",
    "cy49t2_harmonie_arome_eps",
    "cy49t2_harmonie_arome_target",
    "alaro",
    "arome",
    "harmonie_arome",
    "cy49t2_alaro_operational_tomorrow",
    "cy49t2_arome_large_domain_operational",
    "cy49t2_harmonie_arome_large_domain_use_offline",
  ]
  # tag = "v0_23_0_"
  # Comment subtags for default compiler runs only
  subtags = [
    {intel_ = []},
    {gnu_ = ["deode/data/config_files/modifications/submission/atos_bologna_gnu.toml"]},
  ]

[include]
  cases = "config_files/case_definitions.toml"
  macros = "config_files/macros.toml"
  modifs = "config_files/modifs_atos_bologna.toml"
