[general]
  # selection = [ ]
  # tag = "v0_23_0_"

[general.subtags.gnu_]
  active = true
  exclude = ["cy48t2", "cy46h"]
  extra = ["deode/data/config_files/modifications/submission/atos_bologna_gnu.toml"]

[general.subtags.intel_]
  active = true


[include]
  cases = "case_definitions.toml"
  macros = "macros.toml"
  modifs = "modifs_atos_bologna.toml"
