[general]
  selection = ["cy49t2_alaro", "cy49t2_alaro_target"]

[ial]
  active = false
  build_tar_path = "/scratch/deployde330"
  ial_hash = "2951f1a1dc2df82471e857a3331df8bb35050745"
  user_binary_path = "/scratch/@USER@/ial_binaries"

[include]
  cases = "case_definitions.toml"

[macros.case]
  gen_macros = [{ial_hash = "ial.ial_hash"}, {user_binary_path = "ial.user_binary_path"}]
  group_macros = []
  os_macros = ["USER"]

[macros.select.default]
  gen_macros = []
  group_macros = ["modif_macros"]
  os_macros = ["USER"]

[modifs.cleaning.PostMortem.ecf_files]
  active = false

[modifs.general]
  case = "@CASE_PREFIX@@CYCLE@_@CSC@_@EVENT_TYPE@_@DOMAIN@_@YMD_START@@CASE_SUFFIX@"

[modifs.general.times]
  # counter for starting days, this is to test different days
  end = "-P1D"
  start = "-P1D"

[modifs.submission]
  bindir = "@USER_BINARY_PATH@/@IAL_HASH@/@COMPILER@/R64/bin"
  max_ecf_tasks = 25

[modifs.submission.task_exceptions.Forecast]
  bindir = "@USER_BINARY_PATH@/@IAL_HASH@/@COMPILER@/@PRECISION@/bin"

[modifs.system]
  # Picks up the case name and domain from the host run
  host_case = "@HOST_CASE@"
  host_domain = "@HOST_DOMAIN@"
