# General config
# dry means just produce the config files, can be achived by adding "-d" on command line as well
# selection is selection of cases to run
# tag is the label added in front of each case
# subtags allows to loop over additional settings, e.g. for compiler
#

# Config per case
# Place local changes under [cases.x.modifs...]
#  start sets days backwards from today for general.times.start
#  base gives the config to start from
#  host defines the forcing run for a target run
#  extra is extra config files to add

[cases.alaro]

[cases.arome]

[cases.cy46h1_harmonie_arome]

[cases.cy46h1_harmonie_arome_target]
  host = "cy46h1_harmonie_arome"

[cases.cy46h1_harmonie_arome_target.modifs.suite_control]
  mirror_host_case = true

[cases.cy48t3_alaro]

[cases.cy48t3_arome]

[cases.cy48t3_arome_target]
  host = "cy48t3_arome"

[cases.cy48t3_arome_target.modifs.suite_control]
  mirror_host_case = true

[cases.cy49t2_alaro]

[cases.cy49t2_alaro_ddh]
  base = "cy49t2_alaro"
  extra = ["deode/data/config_files/modifications/ddh.toml"]

[cases.cy49t2_alaro_ddh.modifs.system]
  case_suffix = "_ddh"

[cases.cy49t2_alaro_eps]
  base = "cy49t2_alaro"
  extra = [
    "deode/data/config_files/include/eps/eps_7members.toml",
    "deode/data/config_files/include/eps/alaro.toml",
  ]

[cases.cy49t2_alaro_eps.modifs.eps.general]
  members = "0:3"

[cases.cy49t2_alaro_eps.modifs.general.times]
  end = "-P1D"
  start = "-P1D"

[cases.cy49t2_alaro_eps.modifs.system]
  case_suffix = "_eps"

[cases.cy49t2_alaro_operational_tomorrow]
  base = "cy49t2_alaro"
  extra = ["deode/data/config_files/modifications/operational_settings.toml"]

[cases.cy49t2_alaro_operational_tomorrow.modifs.archiving.prefix]
  ecfs = "ec:/@USER@/DE_NWP/deode/@COMPILER@/"

[cases.cy49t2_alaro_operational_tomorrow.modifs.extractsqlite]
  sqlite_path = "@CASEDIR@/sqlite/@SQLITE_MODEL_NAME@/FCTABLE"

[cases.cy49t2_alaro_operational_tomorrow.modifs.general]
  event_type = "nwp"

[cases.cy49t2_alaro_operational_tomorrow.modifs.general.times]
  end = "P1D"
  start = "P1D"

[cases.cy49t2_alaro_operational_tomorrow.modifs.system]
  case_suffix = "_oper_tomorrow"
  scratch_oper = "@SCRATCH@/DE_NWP/deode/@COMPILER@"

[cases.cy49t2_alaro_target]
  host = "cy49t2_alaro"

[cases.cy49t2_alaro_target.modifs.suite_control]
  mirror_host_case = true

[cases.cy49t2_arome]

[cases.cy49t2_arome_ddh]
  base = "cy49t2_arome"
  extra = ["deode/data/config_files/modifications/ddh.toml"]

[cases.cy49t2_arome_ddh.modifs.system]
  case_suffix = "_ddh"

[cases.cy49t2_arome_eps]
  base = "cy49t2_arome"
  extra = [
    "deode/data/config_files/include/eps/eps_7members.toml",
    "deode/data/config_files/include/eps/arome.toml",
  ]

[cases.cy49t2_arome_eps.modifs.eps.general]
  members = "0:3"

[cases.cy49t2_arome_eps.modifs.general.times]
  end = "-P1D"
  start = "-P1D"

[cases.cy49t2_arome_eps.modifs.system]
  case_suffix = "_eps"

[cases.cy49t2_arome_flooding]
  base = "cy49t2_arome"
  extra = ["deode/data/config_files/modifications/event_type/flooding.toml"]

[cases.cy49t2_arome_flooding.modifs.general.times]
  end = "-P1D"
  start = "-P1D"

[cases.cy49t2_arome_large_domain_operational]
  base = "arome"
  extra = ["deode/data/config_files/modifications/operational_settings.toml"]

[cases.cy49t2_arome_large_domain_operational.modifs.archiving.prefix]
  ecfs = "ec:/@USER@/DE_NWP/deode/@COMPILER@/"

[cases.cy49t2_arome_large_domain_operational.modifs.extractsqlite]
  sqlite_path = "@CASEDIR@/sqlite/@SQLITE_MODEL_NAME@/FCTABLE"

[cases.cy49t2_arome_large_domain_operational.modifs.general]
  event_type = "nwp"

[cases.cy49t2_arome_large_domain_operational.modifs.general.times]
  end = "-P1D"
  start = "-P1D"

[cases.cy49t2_arome_large_domain_operational.modifs.system]
  case_suffix = "_oper"
  scratch_oper = "@SCRATCH@/DE_NWP/deode/@COMPILER@"

[cases.cy49t2_arome_R64]
  base = "cy49t2_arome"

[cases.cy49t2_arome_R64.modifs.submission]
  precision = "R64"

[cases.cy49t2_arome_R64.modifs.system]
  case_suffix = "_R64"

[cases.cy49t2_arome_target]
  host = "cy49t2_arome_R64"

[cases.cy49t2_arome_target.modifs.suite_control]
  mirror_host_case = true

[cases.cy49t2_arome_use_offline]
  base = "cy49t2_arome"
  extra = ["deode/data/config_files/modifications/use_surfex_offline_for_prep.toml"]

[cases.cy49t2_arome_use_offline.modifs.general.times]
  end = "-P1D"
  start = "-P1D"

[cases.cy49t2_arome_use_offline.modifs.system]
  case_suffix = "_use_offline"

[cases.cy49t2_harmonie_arome]

[cases.cy49t2_harmonie_arome_ddh]
  base = "cy49t2_harmonie_arome"
  extra = ["deode/data/config_files/modifications/ddh.toml"]

[cases.cy49t2_harmonie_arome_ddh.modifs.system]
  case_suffix = "_ddh"

[cases.cy49t2_harmonie_arome_airquality]
  base = "cy49t2_harmonie_arome"
  extra = ["deode/data/config_files/modifications/event_type/airquality.toml"]

[cases.cy49t2_harmonie_arome_airquality.modifs.archiving.FDB.fdb.surfex_grib2]
  active = false

[cases.cy49t2_harmonie_arome_eps]
  base = "cy49t2_harmonie_arome"
  extra = [
    "deode/data/config_files/include/eps/eps_7members.toml",
    "deode/data/config_files/include/eps/harmonie_arome.toml",
  ]

[cases.cy49t2_harmonie_arome_eps.modifs.eps.general]
  members = "0:3"

[cases.cy49t2_harmonie_arome_eps.modifs.general.times]
  end = "-P2D"
  start = "-P2D"

[cases.cy49t2_harmonie_arome_eps.modifs.system]
  case_suffix = "_eps"

[cases.cy49t2_harmonie_arome_large_domain_use_offline]
  base = "harmonie_arome"
  extra = ["deode/data/config_files/modifications/use_surfex_offline_for_prep.toml"]

[cases.cy49t2_harmonie_arome_large_domain_use_offline.modifs.general.times]
  end = "-P1D"
  start = "-P1D"

[cases.cy49t2_harmonie_arome_large_domain_use_offline.modifs.system]
  case_suffix = "_use_offline"

[cases.cy49t2_harmonie_arome_R64]
  base = "cy49t2_harmonie_arome"

[cases.cy49t2_harmonie_arome_R64.modifs.submission]
  precision = "R64"

[cases.cy49t2_harmonie_arome_R64.modifs.system]
  case_suffix = "_R64"

[cases.cy49t2_harmonie_arome_target]
  host = "cy49t2_harmonie_arome_R64"

[cases.cy49t2_harmonie_arome_target.modifs.suite_control]
  mirror_host_case = true

[cases.harmonie_arome]
  base = "harmonie_arome"
