[general]

[ial]
  active = true
  build_tar_path = "/scratch/project_465000527/github-actions"
  ial_hash = "a7eb2d4356028de422168ca126721ec2eef930a8"
  user_binary_path = "/scratch/project_465000527/@USER@/ial_binaries"

[ial.tests.gnu]
  R32 = ["arome", "harmonie_arome"]
  R64 = ["alaro", "arome", "harmonie_arome"]

[macros.case]
  gen_macros = [
     {ial_hash = "ial.ial_hash"},
     {user_binary_path = "ial.user_binary_path"}
  ]
  group_macros = []
  os_macros = ["USER"]

[macros.select.default]
  gen_macros = []
  group_macros = ["modif_macros"]
  os_macros = ["USER"]

[modifs.general]
  case = "@CASE_PREFIX@@COMPILER@_@PRECISION@_@CYCLE@_@CSC@_@DOMAIN@_@YMD_START@"

[modifs.general.times]
  end = "-P1D"
  start = "-P1D"

[modifs.scheduler.ecfvars]
  case_prefix = "@USER@_@TAG@@SUBTAG@"

[modifs.submission]
  user_binary_path = "/scratch/project_465000527/@USER@/ial_binaries"
  max_ecf_tasks = 10
  bindir = "@USER_BINARY_PATH@/@IAL_HASH@/@COMPILER@/R64/bin"

[modifs.submission.task_exceptions.Forecast]
  bindir = "@USER_BINARY_PATH@/@IAL_HASH@/@COMPILER@/@PRECISION@/bin"

[modifs.submission.task_exceptions.PgdFilterTownFrac.ENV]
  ECF_TRIES = 15

[modifs.submission.types.serial.BATCH]
  MEM = "#SBATCH --mem=0GB"
  PARTITION = "#SBATCH --partition=standard"

[modifs.suite_control]
  create_static_data = true
  do_archiving = false
  do_creategrib_static = false
  do_extractsqlite = false
  do_mergesqlite = false

