[general]

[ial]
  active = true
  bindir = "/scratch/project_465000527/@USER@/ial_binaries/@IAL_HASH@/@COMPILER@/@PRECISION@/bin"
  build_tar_path = "/scratch/project_465000527/github-actions"
  ial_hash = "a7eb2d4356028de422168ca126721ec2eef930a8"

[ial.tests.gnu]
  R32 = ["arome", "harmonie_arome"]
  R64 = ["alaro", "arome", "harmonie_arome"]

[macros.case]
  gen_macros = [{ial_hash = "ial.ial_hash"}]
  group_macros = []
  os_macros = ["USER"]

[macros.select.default]
  gen_macros = []
  group_macros = ["modif_macros"]
  os_macros = ["USER"]

[modifs.general]
  case = "@CASE_PREFIX@@DOMAIN@_@YMD_START@"

[modifs.general.times]
  end = "-P1D"
  start = "-P1D"

[modifs.submission]
  max_ecf_tasks = 10

[modifs.suite_control]
  create_static_data = true
  do_archiving = false
  do_creategrib_static = false
  do_extractsqlite = false
  do_mergesqlite = false
