# Global modifications
[modifs.archiving.FDB.fdb.fpgrib_files]
  active = false

[modifs.cleaning.PostMortem.ecf_files]
  active = false

[modifs.fdb.expver_restrictions]
  test = ["snh02", "lrb_465000527_efdev"]
  ulfs = ["snh", "andraeul"]

[modifs.fdb.grib_set]
  expver = "0098"

[modifs.general.times]
  # counter for starting days, this is to test different days
  end = "-P@COUNTER@D"
  start = "-P@COUNTER@D"

[modifs.macros.select.release_test]
  os_macros = ["PERM"]

[modifs.platform.mirrorglobalDT]
  remote_host = "ecflow-gen-snh02-001"
  remote_path = "/mirror_globalDT_iekm/pabv/iekm/fc/main/fcgroup/00/model"

[modifs.scheduler.ecfvars]
  case_prefix = "@TAG@@SUBTAG@"
  ecf_files = "@PERM@/deode_ecflow/ecf_files"
  ecf_files_remotely = "@PERM@/deode_ecflow/ecf_files"
  ecf_home = "@PERM@/deode_ecflow/jobout"
  ecf_jobout = "@PERM@/deode_ecflow/jobout"
  ecf_out = "@PERM@/deode_ecflow/jobout"

[modifs.submission]
  max_ecf_tasks = 10

[modifs.suite_control]
  do_archiving = false

[modifs.system]
  # Picks up the case name and domain from the host run
  host_case = "@HOST_CASE@"
  host_domain = "@HOST_DOMAIN@"
