[modifs.fdb.expver_restrictions]
  9999 = ["snh02"]

[modifs.fdb.grib_set]
  expver = "9999"

[modifs.general]
  case = "@CASE_PREFIX@@CYCLE@_@CSC@_@EVENT_TYPE@_@DOMAIN@_@YMD_START@@CASE_SUFFIX@"

[modifs.general.times]
  # counter for starting days, this is to test different days
  end = "-P@COUNTER@D"
  start = "-P@COUNTER@D"

[modifs.scheduler.ecfvars]
  case_prefix = "@TAG@@SUBTAG@"

[modifs.submission.task_exceptions.PgdFilterTownFrac.ENV]
  ECF_TRIES = 15

[modifs.system]
  # Picks up the case name and domain from the host run
  case_suffix = ""
  host_case = "@HOST_CASE@"
  host_domain = "@HOST_DOMAIN@"
  test_data_path = "/perm/snh/ttr/data"
