# Global modifications
[modifs.archiving.FDB.fdb.fpgrib_files]
  active = true

[modifs.boundaries]
  max_interpolation_tasks = -1

[modifs.cleaning.PostMortem.ecf_files]
  active = false

[modifs.fdb.expver_restrictions]
  ulfs = ["snh", "andraeul"]

[modifs.fdb.grib_set]
  expver = "ulfs"

[modifs.general.times]
  # counter for starting days, this is to test different days
  end = "-P1D"
  start = "-P1D"

[modifs.scheduler.ecfvars]
  case_prefix = "@USER@_@TAG@@SUBTAG@"

[modifs.submission]
  max_ecf_tasks = 25

[modifs.submission.task_exceptions.PgdFilterTownFrac.ENV]
  ECF_TRIES = 15

[modifs.submission.types.serial.BATCH]
  MEM = "#SBATCH --mem=0GB"
  PARTITION = "#SBATCH --partition=standard"

[modifs.suite_control]
  do_archiving = false
  max_static_data_tasks = -1

[modifs.system]
  # Picks up the case name and domain from the host run
  host_case = "@HOST_NAME@"
  host_domain = "@HOST_DOMAIN@"
